name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        environment: [ubuntu-latest, macos-latest]
        enable_logging: [true, false]

    runs-on: ${{ matrix.environment }}

    steps:
      - uses: actions/checkout@v5

      - name: Install Anchor prerequisites on Ubuntu
        if: ${{ matrix.environment == 'ubuntu-latest' }}
        run: sudo apt update && sudo apt install libudev-dev

      - name: Test
        run: |
          set -x

          # Install Solana
          sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"

          # Make a key
          mkdir -p $HOME/.config/solana
          cp etc/rfc8032_test_vector.json $HOME/.config/solana/id.json

          # Install Anchor
          cargo install --git https://github.com/solana-foundation/anchor --tag v0.32.1 anchor-cli

          # Initialize an Anchor project and test it
          anchor init foo
          cd foo
          export RUST_LOG="$(${{ matrix.enable_logging }} && echo -n debug)"
          ../anchor-test-hack.sh foo
          cat test-ledger/validator.log | grep DEBUG
